### ISSUE TITLE
Scenario: Add expense

### ISSUE THREAD

**Issue by kmatsuleva** [kmatsuleva/scrum#1]
Given that Joe has already logged in
When Joe says, “I want to add an expense”
Then Joe sees a form for creating a new expense
When Joe fills out the form, specifies the amount and category of expense
Then system saves request

**Comment by mgenov** [comment]
The scenarios need to be in the same issue as the user story.

**Comment by mgenov** [comment]
I suppose "Add expense" is the name of the user story, but it's not valuable of it's own. It is similar to register user. 

Every User story should follow the invest principle: 
https://en.wikipedia.org/wiki/INVEST_(mnemonic)

In this case, the real values comes from the tracking of expenses and here are my 2 cents:

 * track company expenses (happy path)
Flow: user enter name and amount of the expense and registers it. After then goes to the all expenses page and sees all entered expenses, **e.g** the user is able to enter expenses and to see them after this functionality is implemented. 

 * report company expenses for a period of time
Flow: user selects from and to dates and clicks report button and the system displays expenses for that period, **e.g** user is now able to filter the expenses 

 * suggested expenses entering 
 Flow: user types some character in the expenses name and the system suggests names of already entered expenses that are matching the entered keywords.

**Comment by kmatsuleva** [comment]
@mgenov I created two issues. Could you look at them again?
